Patch wp_delete_file_from_directory
presslabs/wordpress-composer-builder pull request #2
Opened 2019-03-14 13:59 UTC by vtemian

Check if the file to delete uses stream wrappers. If so, don't check it's `realpath` since PHP doesn't support stream wrappers in `realpath` implementation.

2019-03-18 13:21 UTC, calind requested changes

2019-03-18 13:21 UTC, calind commented on patches/real_path_5.0.diff
> ++	$file_path      = wp_normalize_path( $file ) ;
```suggestion
+	$file_path      = wp_is_stream( $file ) ? wp_normalize_path( $file ) : realpath( wp_normalize_path( $file ) ) ;
```

2019-03-18 13:21 UTC, calind commented on patches/real_path_5.0.diff
> ++	$directory_path = wp_normalize_path( $directory ) ;
```suggestion
+	$directory_path = wp_is_stream( $directory ) ? wp_normalize_path( $directory ) : realpath( wp_normalize_path( $file ) );
```

2019-03-19 10:53 UTC, vtemian commented on patches/real_path_5.0.diff
> ++	$file_path      = wp_normalize_path( $file ) ;
Done.

2019-03-19 10:53 UTC, vtemian commented on patches/real_path_5.0.diff
> ++	$directory_path = wp_normalize_path( $directory ) ;
Done.

2019-03-19 13:38 UTC, calind approved these changes

2019-03-19 13:39 UTC, merged